-- Insert SIS Cert certificate for PT Central Georgette
INSERT INTO public.certificates (
  certificate_number,
  company_name,
  certificate_standard,
  issue_date,
  surveillance_date,
  expiry_date,
  certification_body,
  accreditation_body,
  template_type,
  address,
  certified_location,
  country,
  issue,
  first_issue_date,
  latest_issue_date,
  recertification_date,
  ea_code,
  scope,
  status
) VALUES (
  'QMS-0096',
  'PT Central Georgette',
  'ISO 9001:2015',
  '2024-08-12',
  '2025-08-11',
  '2027-08-11',
  'SIS Certifications',
  'KAN',
  'siscert',
  'Jl. Jend. A. Yani No. 1-3, Pejagalan, Penjaringan, Jakarta Utara 14450, Indonesia',
  'Jl. Jend. A. Yani No. 1-3, Pejagalan, Penjaringan, Jakarta Utara 14450, Indonesia',
  'Indonesia',
  'ISSUE NO.1',
  '2024-08-12',
  '2024-08-12',
  '2027-05-12',
  'EA 28',
  'Manufacturing and Trading of Synthetic Fabrics',
  'active'
);